# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

campaignchain_activity_twitter_update_status_new:
    pattern:  /activity/twitter/update-status/new
    defaults: { _controller: campaignchain.activity.controller.twitter.update_status:newAction }

campaignchain_activity_twitter_update_status_edit:
    pattern:  /activity/twitter/update-status/{id}/edit
    defaults: { _controller: campaignchain.activity.controller.twitter.update_status:editAction }

campaignchain_activity_twitter_update_status_edit_modal:
    pattern:  /modal/activity/twitter/update-status/{id}/edit
    defaults: { _controller: campaignchain.activity.controller.twitter.update_status:editModalAction }

campaignchain_activity_twitter_update_status_edit_api:
    pattern:  /api/v1/activity/twitter/update-status/byactivity/{id}/edit
    defaults: { _controller: campaignchain.activity.controller.twitter.update_status:editApiAction }
    options:
        expose: true

campaignchain_activity_twitter_update_status_read:
    pattern:  /activity/twitter/update-status/{id}
    defaults: { _controller: campaignchain.activity.controller.twitter.update_status:readAction }