# Copyright 2016 CampaignChain, Inc. <info@campaignchain.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

parameters:
    campaignchain.activity.twitter.update_status:
        bundle_name: "campaignchain/activity-twitter"
        module_identifier: "campaignchain-twitter-update-status"
        location: "%campaignchain.location.twitter.status%"
        equals_operation: true
        operations:
            - "%campaignchain.operation.twitter.update_status%"
        handler: "campaignchain.activity.controller.handler.twitter.update_status"
        validator: "campaignchain.activity.validator.twitter.update_status"
        hooks_options:
            campaignchain-image:
                number_of_images: 4

services:
    campaignchain.activity.controller.twitter.update_status:
        class: CampaignChain\CoreBundle\Controller\Module\ActivityModuleController
        calls:
            - [setContainer, ["@service_container"]]
            - [setParameters, ["%campaignchain.activity.twitter.update_status%"]]
    campaignchain.activity.controller.handler.twitter.update_status:
        class: CampaignChain\Activity\TwitterBundle\Controller\UpdateStatusHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@campaignchain.operation.twitter.status"
            - "@campaignchain.channel.twitter.rest.client"
            - "@campaignchain.job.operation.twitter.update_status"
            - "@session"
            - "@templating"
            - "@campaignchain.activity.validator.twitter.update_status"
    campaignchain.activity.validator.twitter.update_status:
        class: CampaignChain\Activity\TwitterBundle\Validator\UpdateStatus
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@campaignchain.channel.twitter.rest.client"
            - "%campaignchain_channel_twitter.max_duplicate_interval%"
            - "@campaignchain.core.util.scheduler"