# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    campaignchain.activity.twitter.update_status:
        activity_bundle_name: "campaignchain/activity-twitter"
        activity_module_identifier: "campaignchain-twitter-update-status"
        operation_bundle_name: "campaignchain/operation-twitter"
        operation_module_identifier: "campaignchain-twitter-update-status"
        location_bundle_name: "campaignchain/location-twitter"
        location_module_identifier: "campaignchain-twitter-status"
        equals_operation: true
        operation_forms:
            - "CampaignChain\Operation\TwitterBundle\Form\Type\UpdateStatusOperationType"
        operation_job: "campaignchain.job.operation.twitter.update_status"

services:
    campaignchain.activity.controller.twitter.update_status:
        class: CampaignChain\CoreBundle\Controller\Module\ActivityModuleController
        calls:
            - [setContainer, [@service_container]]
            - [setParameters, ["%campaignchain.activity.twitter.update_status%"]]